spring:
#登录国际化基础名称加载......
  messages:
    basename: i18n\login
#数据源
  datasource:
    username: root
    password: a1b2c3
    #虚拟机地址
#    url: jdbc:mysql://192.168.13.128:3306/springboot?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8

    #windows下的地址和数据库名称
    url: jdbc:mysql://121.89.212.3:3306/springcrudrestful?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#采用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  #添加更对数据源配置 需要在configuration里将这些属性赋值给 DruidDateSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    filters: stat,wall,log4j


#thymeleaf引擎模板缓存
  thymeleaf:
    cache: false
#from表单可通过input修改请求方式 put delete
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#连接Redis  采用的是CentOS.7 地址为linux的地址
  redis:
    host: 121.89.212.3
    port: 6379
    client-name:
#ql语句日志
#logging:
#  level:
#    com.review.rustfulcrud.mapper: debug
#debug: true
